---
# this is file yaml
- name: file yaml
  hosts: server1
  become: true
  
  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False 

  roles:
    - role: common
    - role: mysql

  handlers: 
    - import_tasks: handlers/main.yml
