---
# this is file yaml
- name: This is file yaml
  hosts: server1
  become: true
  
  vars:
    mysql_root_password: password
    group_vars: all


  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False 

  roles:
    - role: common
    - role: mysql

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
