---

- name: Recreate host keys - collect old host keys
  shell: ls /etc/ssh/ssh_host_*
  register: ssh_host_keys
  ignore_errors: true


- name: Recreate host keys - delete old keys
  file:
  name: '{{ item }}'
  state: absent
  loop: '{{ ssh_host_keys.stdout_lines | default([]) }}'

- name: Recreate host keys - create new keys 1/3
  command: dpkg-reconfigure openssh-server

- name: Recreate host keys - create new keys 2/3
  file:
    name: /etc/ssh/ssh_host_rsa_key
    state: absent

- name: Recreate host keys - create new keys 3/3
  command: ssh-keygen -t rsa -b 4096 -N '' -f /etc/ssh/ssh_host_rsa_key
  notify: restart ssh

- name: Remove old host key from known_hosts file
  known_hosts:
    name: '{{ item }}'
    state: absent
  loop:
    - '{{ inventory_hostname }}'
    - "`dig +short {{ inventory_hostname }}`"
  delegate_to: localhost

- name: Collect new host entries for known_hosts file
  shell: "ssh-keyscan -t ed25519,rsa {{ inventory_hostname }},`dig +short {{ inventory_hostname }}`"
  register: ssh_known_host_results
  ignore_errors: true
  delegate_to: localhost

- name: Add new host key to known_hosts file
  known_hosts:
    name: '{{ inventory_hostname }}'
    key: '{{ ssh_known_host_results.stdout }}'
    state: present
  delegate_to: localhost
  when: ssh_known_host_results.stdout != ""
